### ISSUE TITLE
The Map

### ISSUE THREAD

**Issue by unickorn** [survanetwork/HotBlock#10]
Could you provide the map shown in the example picture?

**Comment by jarne** [comment]
Here it is: [HotBlock.zip](https://github.com/survanetwork/HotBlock/files/1120370/HotBlock.zip)

**Comment by unickorn** [comment]
Is it just me or is the map corrupted? It appears to be an empty world for me.

**Comment by jarne** [comment]
Works for me, it's just a Minecraft (PC Edition) Anvil world for 1.8. If you want to use it with PocketMine, you should convert it to McRegion or PMAnvil.

**Comment by unickorn** [comment]
Converted it to McRegion and tried on my server, didn't work.
Tried opening the normal Anvil world on MCPE 1.8, still didn't work.

Are you sure you've sent me the true file?

**Comment by jarne** [comment]
Maybe you are at the wrong coordinates? The building is located at (874; 8; -658).

**Comment by unickorn** [comment]
Yayyy! It worked!
