### ISSUE TITLE
Could not load plugin 'HotBlock': Unknown dependency / Circular dependency detected

### ISSUE THREAD

**Issue by teracube** [survanetwork/HotBlock#13]
Hi,

Server is unable to load latest plugin
https://poggit.pmmp.io/r/9205/HotBlock.phar

Log :
2017-08-01 [07:51:22] [Server thread/CRITICAL]: Could not load plugin 'HotBlock': Unknown dependency
2017-08-01 [07:51:22] [Server thread/CRITICAL]: Could not load plugin 'HotBlock': Circular dependency detected

PocketMine-MP version 1.6.2dev-339 "Unleashed" (API 3.0.0-ALPHA7)

additional information 
same issue resolved by developer with plugin KillMney
https://forums.pmmp.io/conversations/killmoney-alpha7.914/
same pb with economytapi

thanks

**Comment by unickorn** [comment]
HotBlock won't work without EconomyAPI.
Make sure you get EconomyAPI working before considering the issue is with HotBlock.

**Comment by jarne** [comment]
The conversation doesn't exist any more - is the issue still relevant?

**Comment by teracube** [comment]
it's now ok
thanks
