### ISSUE TITLE
Add a leaderboard

### ISSUE THREAD

**Issue by shavindanagapen** [survanetwork/HotBlock#19]
Can you please add a leaderboard that we can place inside of the map? Please. Or add a timer and at the end the player with the most points win?

**Comment by jarne** [comment]
A timer or a time limit is not planned because it's a never-ending game where you can get money for the economy plugin all the time. I'll add a statistics leaderboard as a feature request soon.

**Comment by shavindanagapen** [comment]
Yes, please! Thank you so much. A statistic leaderboards will be the best for this plugin! May I have an expected date of when this enhancement will be done?

**Comment by NenadGvozdenac** [comment]
Why not make your own plugins but asking for public ones to be remade, just because of your small server?
