### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by kmorales13** [survanetwork/HotBlock#31]
### ❗️ Please describe the issue

Server crashes the moment I join the world which has HotBlock activated.

### ✅ How should it usually work?

[ ... ]

### 🗂 Steps to reproduce

1. Downloaded example world from readme
2. Placed it under the server's worlds directory
3. Updated config with world's name
4. Restarted server
5. Used MultiWorld to tp to world
6. Server crashes

`[Server thread/INFO]: Preparing world "HotBlock"`
`[Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "plugins/HotBlock.phar/src/surva/hotblock/tasks/PlayerCoinGiveTask" at line 59`

### 🌱 Environment

Version of this plugin: 1.1.4
Version of PocketMine-MP: 3.11.6

Version of PHP: 7
OS: Ubuntu 18.04.4 LTS

**Comment by Grumpypjs08** [comment]
i have the same problem!

**Comment by Grumpypjs08** [comment]
i have the same problem!

**Comment by Grumpypjs08** [comment]
i crashed my server for the first time while i was in the game.

**Comment by jarne** [comment]
Thanks for reporting 👍 Should be fixed in the latest version
