### ISSUE TITLE
Suggestion | MultiEconomy Support

### ISSUE THREAD

**Issue by BroCrows** [survanetwork/HotBlock#33]
### 💭 What should be added or changed regarding this plugin?
Add an option to use MultiEconomy instead of EconomyAPI!
[ ... ]

**Comment by jarne** [comment]
Seems like MultiEconomy isn't updated anymore and isn't compatible with PocketMine v4. Providers for other economy plugins like Capital and BedrockEconomy have been recently added (855dc92aee0a39d6a99a2795739ce3e717a6b439 & 11c88976ee4f4e97abc0d3428e81aa512ecf845f).
