### ISSUE TITLE
switch from MultiEconomiApi to Coins

### ISSUE THREAD

**Issue by EquineBee20418** [survanetwork/HotBlock#34]
### 💭 What should be added or changed regarding this plugin?

[ ... ]
Hello, I would like the plugin instead of having the support of EconomíApi had another system like Coins I tried to change it but gives me error can help me?

**Comment by jarne** [comment]
Providers for other economy plugins like Capital and BedrockEconomy have been recently added (855dc92aee0a39d6a99a2795739ce3e717a6b439 & 11c88976ee4f4e97abc0d3428e81aa512ecf845f). I couldn't find any reference to a economy plugin called "Coins". If you have questions about implementing another economy plugin by yourself, please ask on our Discord (see Readme) and provide an error message.
