### ISSUE TITLE
Bug With Plugin Slapper

### ISSUE THREAD

**Issue by thinh2118** [survanetwork/HotBlock#35]
When use /slapper remove, plugin HotBlock will have bug Call to a member function getBlock() on null" (EXCEPTION) in "plugins/HotBlock_v1.1.3/src/surva/hotblock/EventListener" at line 29

**Comment by jarne** [comment]
There's a player entity check missing in the plugin's code at https://github.com/survanetwork/HotBlock/blob/master/src/surva/hotblock/EventListener.php#L32, I'll fix this soon.
