### ISSUE TITLE
Quartz Block stops working.

### ISSUE THREAD

**Issue by hezuwy** [survanetwork/HotBlock#37]
### ❗️ Please describe the issue

Quartz block stopped working. Even if I restart the server. The wood still has safezone and netherack still has poison. Idk why Quartz Block isnt..

### ✅ How should it usually work?

It should always work right?

### 🗂 Steps to reproduce

1. [ First step ]
2. [ First second ]
3. [ And so on ... ]

### 🌱 Environment

Version of this plugin: Using the HotBlock v1.1.5 build &18316
Version of PocketMine-MP: Latest

**Comment by jarne** [comment]
Has been fixed with the latest release
