### ISSUE TITLE
Commands?

### ISSUE THREAD

**Issue by jeffreyvarga** [survanetwork/HotBlock#9]
What are the commands?

**Comment by jarne** [comment]
There are no commands

**Comment by jeffreyvarga** [comment]
Then how do i use this plugin?

**Comment by jarne** [comment]
You need to build a world like described in the README and set the name of this world in the config

**Comment by jeffreyvarga** [comment]
Thankyou, but do I use the same blocks as the example?

**Comment by jarne** [comment]
Yes
